#ifndef SETTINGS_INCLUDED
#define SETTINGS_INCLUDED


#define SESSION_DIRECTORY ""
#define UPLOADED_FILES_DIRECTORY ""
#define PERMENENT_FILES ""
#define DEFAULT_STATIC_DIRECTORY ""
#define BUILTIN_STATIC_DIRECTORY ""
#define USE_SSL
#define DEBUG
#endif
